### ISSUE TITLE
ECONFLICT     Unable to find suitable version for font-awesome

### ISSUE THREAD

**Issue by remodeling-com-dev** [BlackrockDigital/startbootstrap-sb-admin-2#138]
There is a conflict because of using FontAwesome versions 4.6.3 and 4.2.0 in same time I think

```
bower resolved      git://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#3.3.7+1
bower cached        https://github.com/twbs/bootstrap.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#~3.3.7
bower cached        https://github.com/DataTables/DataTables.git#1.10.12
bower validate      1.10.12 against https://github.com/DataTables/DataTables.git#~1.10.4
bower cached        https://github.com/DataTables/Plugins.git#1.0.1
bower validate      1.0.1 against https://github.com/DataTables/Plugins.git#~1.0.1
bower cached        https://github.com/flot/flot.git#0.8.3
bower validate      0.8.3 against https://github.com/flot/flot.git#~0.8.3
bower cached        https://github.com/FortAwesome/Font-Awesome.git#4.6.3
bower validate      4.6.3 against https://github.com/FortAwesome/Font-Awesome.git#~4.6.3
bower cached        https://github.com/imsky/holder.git#2.4.1
bower validate      2.4.1 against https://github.com/imsky/holder.git#~2.4.1
bower cached        https://github.com/onokumus/metisMenu.git#1.1.3
bower validate      1.1.3 against https://github.com/onokumus/metisMenu.git#~1.1.3
bower cached        https://github.com/morrisjs/morris.js.git#0.5.1
bower validate      0.5.1 against https://github.com/morrisjs/morris.js.git#~0.5.1
bower cached        https://github.com/DataTables/Responsive.git#1.0.6
bower validate      1.0.6 against https://github.com/DataTables/Responsive.git#1.0.6
bower cached        https://github.com/lipis/bootstrap-social.git#4.8.0
bower validate      4.8.0 against https://github.com/lipis/bootstrap-social.git#~4.8.0
bower cached        https://github.com/krzysu/flot.tooltip.git#0.8.7
bower validate      0.8.7 against https://github.com/krzysu/flot.tooltip.git#~0.8.4
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#>=1.7.0
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#>= 1.2.6
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#>= 2.1.0
bower cached        https://github.com/DmitryBaranovskiy/raphael.git#2.2.1
bower validate      2.2.1 against https://github.com/DmitryBaranovskiy/raphael.git#>= 2.0
bower cached        https://github.com/mochajs/mocha.git#1.17.1
bower validate      1.17.1 against https://github.com/mochajs/mocha.git#~1.17.1
bower cached        https://github.com/FortAwesome/Font-Awesome.git#4.2.0
bower validate      4.2.0 against https://github.com/FortAwesome/Font-Awesome.git#~4.2
bower cached        https://github.com/adobe-webplatform/eve.git#eef80ed
bower validate      eef80ed against https://github.com/adobe-webplatform/eve.git#eef80ed
bower short-sha     Consider using longer commit SHA to avoid conflicts
bower ECONFLICT     Unable to find suitable version for font-awesome
rake aborted!
Command failed with status (1): [/usr/local/bin/bower install -p ...]
```

**Comment by remodeling-com-dev** [comment]
Update:

```
Unable to find a suitable version for font-awesome, please choose one by typing one of the numbers below:
    1) font-awesome#~4.2 which resolved to 4.2.0 and is required by bootstrap-social#4.8.0
    2) font-awesome#~4.6.3 which resolved to 4.6.3 and is required by sb_admin#3.3.7+1
```

**Comment by remodeling-com-dev** [comment]
Fixed by adding the following line in Bowerfile:

```
resolution "font-awesome", "~4.6.3"
```

**Comment by davidtmiller** [comment]
Yeah I snuck that guy in there. It should be working fine at this point :)

**Comment by WaveHack** [comment]
I'm still having issues with this.

Minimal test case, create empty directory with the following contents in `bower.json`:

```JSON
{
  "name": "test",
  "dependencies": {
    "startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master"
  }
}
```

Now run `bower install`. Still gives problems as described in the topip. This is of course manually using this repo, because the bower package is still pointing to ironsummitmedia.

Either setting the resolution in the bowerfile as mentioned by remodeling-com-dev or using a specific commit (6b5d5953b67dbe830fee993de3693dc437078a8d in this case) does fix the issue in my case.

But I disagree about the 'it should be working fine' without resorting to either option. Any chance this will get fixed soon?
